name: Pull request Status

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr_status:
    name: pr_status
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: PR status check
       run: |
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.repository = ${{ github.repository }}
     - name: pr check
       env:
         REPO: ${{ github.repository }}
         PR_NUMBER : ${{ github.event.pull_request.number }}
       run: |
          pr_status_check=$(curl -s -X GET https://api.github.com/repos/atulec016/test_demo/pulls/4 -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" | jq '.mergeable_state')
          echo $pr_status_check
          if [ "$pr_status_check" == "unstable" ]; then
            curl -s -X POST https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments -d '{"body": "The pull request cant be merged and is in blocked state"}' -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}"
          fi
