name: test

on:
  issue_comment:
    types: [created]

jobs:
  pr_status_check:
    name: pr_status_check
    runs-on: ubuntu-latest
    if: >
       startsWith(github.event.comment.body, 'testing')
    steps:
     - uses: actions/checkout@v3
     - name: Fetch Branch Name
       id: fetch-branch-name
       uses: xt0rted/pull-request-comment-branch@v1
     - name: Check out code from ${{ steps.fetch-branch-name.outputs.head_ref }}
       uses: actions/checkout@v3
       with:
           ref: ${{ steps.fetch-branch-name.outputs.head_ref }}
     - name: pr check
       env:
         REPO: ${{ github.repository }}
         PR_NUMBER : ${{ github.event.pull_request.number }}
       run: |
          echo ${{ github.event.issue.number }}
          echo ${{ github.event.repository.name }}
          echo $GITHUB_REPOSITORY
          echo ${{ steps.fetch-branch-name.outputs.head_ref }}
