name: Pull Request Demo
run-name: ${{ github.actor }} is running command
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr_status:
    name: pr_status
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: PR status check
       run: |
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
     - name: pr test
       shell: pwsh
       run: |
         $url="https://api.github.com/repos/atulec016/test_demo/pulls/${{ github.event.pull_request.number }}"
         $status=Invoke-RestMethod -Method GET -Uri $url -Headers @{Authorization = "Token ${{ secrets.GIT_TOKEN }}"} -ContentType "application/json"
         Write-Host $status.mergeable_state
         $status_1=$status.mergeable_state
         $url_1="https://api.github.com/repos/atulec016/test_demo/issues/${{ github.event.pull_request.number }}/comments"
         if ($status.mergeable_state -eq "blocked") 
         {
          Invoke-RestMethod -Method POST -Uri $url_1 -Headers @{Authorization = "Token ${{ secrets.GIT_TOKEN }}"} -Body @{"message"= "Pull Request status isn't mergeable" } -ContentType "application/json"
         }else
         {
          Invoke-RestMethod -Method POST -Uri $url_1 -Headers @{Authorization = "Token ${{ secrets.GIT_TOKEN }}"} -Body @{"message"= "Pull Request status is Mergeable"} -ContentType "application/json"
         }
