name: Pull request Status_test

on: 
  push

jobs:
  pr_status:
    name: tag_get
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v4
       with:
           python-version: '3.9'
     - name: install-databricks-cli
       run: |
          pip install databricks-cli --upgrade
          host=https://${{ secrets.DATABRICKS_INSTANCE }}
          echo $host
          echo "DATABRICKS_HOST=${{ env.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ env.DATABRICKS_PAT }}" >> $GITHUB_ENV  
          databricks jobs list --output json
       env:
         DATABRICKS_HOST: https://${{ secrets.DATABRICKS_INSTANCE }}
         DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
     - name: teting
       run: |
          echo ${{ github.workspace }}
          ls
          pwd
          "${{ github.workspace }}/test/testing/test.sh"
