name: Pull request Status_test

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr_status:
    name: pr_status
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v4
       with:
           python-version: '3.9'
     - name: install-databricks-cli
       uses: microsoft/install-databricks-cli@v1.0.0
     - run: databricks --version
     - name: pr check
       env:
         REPO: ${{ github.repository }}
         PR_NUMBER : ${{ github.event.pull_request.number }}
       run: |
          tag=$(curl -s GET https://api.github.com/repos/$REPO/tags\?per_page\=1 -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" | jq -r '.[].name' )
          echo $tag
