name: DB check

on:
 push

jobs:
  pr_status:
    name: tag_get
    environment: test
    runs-on: ubuntu-latest
    steps:
     - name: Check out code from
       uses: actions/checkout@v3
     - uses: actions/setup-python@v4
       with:
           python-version: '3.9'
     - name: tesing
       run: |
          echo ${{ github.workspace }}
          ls
          pwd
          job_id=848514976127742
          tag=v1
          echo $tag
          cat "${{ github.workspace }}/test/testing/test.json"
          cat "${{ github.workspace }}/test/testing/test.json" | jq --arg job_id $job_id --arg group_name ${{ vars.GROUPNAME }} --arg tag $tag '.job_id |= $job_id | (.new_settings.access_control_list[] | .group_name) |= $group_name | (.new_settings.git_source.git_tag) |= $tag' >> reset_job.json
          cat reset.json | jq 'del(.new_settings.git_source.git_branch)' >> reset_job.json
          cat reset.json
          ls
          git status
