name: Tag request Status

on: 
  push:
    tags: 
      - '*'

jobs:
  pr_status:
    name: tag_get
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: pr check
       env:
         REPO: ${{ github.repository }}
         PR_NUMBER : ${{ github.event.pull_request.number }}
       run: |
          echo ${{github.ref}}
