name: Pull request Status

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr_status:
    name: pr_status
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: pr check
       env:
         REPO: ${{ github.repository }}
         PR_NUMBER : ${{ github.event.pull_request.number }}
       run: |
          tag=$(curl -s GET https://api.github.com/repos/$REPO/tags\?per_page\=1 -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" | jq -r '.[].name' )
          $version=${tag:1}
          echo $version
          minor_upgrade= $version + 0.0.1
          curl -X POST https://api.github.com/repos/OWNER/REPO/git/tags -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" -d '{"tag": ${{ minor_upgrade }} }'
