name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub actionssssss 🚀
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  Pipeline_exectuion:
    name: Pipeline_exectuion
    environment: test
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: echo "Pipeline submitted succeessfully"
     
  fetch_status:
    name: fetch status
    #needs:   check_execution_status
    #environment: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{secrets.roles }}
        aws-region: us-west-2
    - uses: actions/checkout@v2
    - id: Fetch_status
      name: Fetch Status
      run: |
         value="Succeeded"
         echo $value
         if [ "$value" == "Succeeded" ]; then
             echo "Pipeline completed successfully"
         elif [ "$value" == "Stopped" ]; then
             step_name=test
             echo "Sagemaker Pipeline has been stopped at step: $step_name"
         elif [ "$value" == "Failed" ]; then
             step_name="testing"
             error_details="getig"
             echo "Sagemaker pipline failed at processing step: $step_name with reason: $error_details"
         fi
    - name: Cloudwatch URL
      run: |
        logstream_value=$(aws logs describe-log-streams --log-group-name '/aws/lambda/test_lambda' --query 'logStreams[*].logStreamName' --max-items 1 --order-by LastEventTime --descending --output json |jq .[] | tr -d '"' | sed 's/\$/\$2524/g' |  sed 's/\[/\$255B/g' | sed 's/\]/\$255D/g' | sed 's|\/|\$252F|g')
        group='/aws/lambda/test_lambda'
        log_group=$(echo $group | sed 's|\/|\$252F|g')
        echo "https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/"$log_group"/log-events"$logstream_value >> GITHUB_SUMMARY
        
